### ISSUE TITLE
[autonity] Make `Logging` verbosity levels configurable 

### ISSUE THREAD

**Issue by raj-shekhar1** [clearmatics/charts-ose-helm3#38] opened 2020-09-16 14:59 UTC
As a user
I want to pass the logging level arguments in values file
So that it can be set to different levels as per the environment/nodes to avoid unnecessary flooding in Elastic search cluster

Options - `--verbosity value 
                  Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default: 3)`

### Acceptance criteria
- [ ] Configurable logging levels

**Comment by Klazomenai** [comment] 2020-09-21 16:44
Closing as duplicate of #27

**Closed as completed** 2020-09-21 18:21 UTC
Labels: wontfix, function:devops
